image: theleede/dlo-runner:latest

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - gradle shadowJar
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

deploy_stage:
  stage: deploy
  only:
    -  develop
  script:
    - export SSHPASS=$USER_PASS
    - cd build/libs/
    - sshpass -e scp -o stricthostkeychecking=no -r . $USER_NAME@$IP_ADDRESS:/opt/api/beta
    - sshpass -e ssh -t $USER_NAME@$IP_ADDRESS "/opt/api/beta/update.sh"
