image: gradle:jdk11

stages:
  - build
  - pages

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle shadowJar
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
pages:
  stage: pages
  script:
    - 'gradle javadoc'
    - 'mv target/site/apidocs public'
  artifacts:
    paths:
      - 'public'
  only:
    - 'master'

